- name: Create a static IP address
  google.cloud.gcp_compute_address:
    name: "{{ instance_name }}"
    region: "{{ zone.split('-')[0] }}-{{ zone.split('-')[1] }}"
    project: "{{ project_id }}"
    auth_kind: serviceaccount
    service_account_file: "{{ service_account_file }}"
    state: present
  register: address